### PR TITLE
Allow the min poll interval to be configured globally

### PR DESCRIPTION
**Pull request by cvanderschuere**
Allow configuration of minimum poll without changing any of the interfaces.

@wonga00 @daveauerbach

### CODE REVIEW

**Comment by rhettg** [comment]
How about some documentation? This seems like some real world usage lessons that might be nice to point out in the README.

**Comment by wonga00** [comment]
i don't really understand how i'd use this in code -- do i call `stream.MinPollInterval = 5.0 * time.Second`?
seems strange to have it be a global variable. How about storing it in the struct ShardStreamReader, and propagate via `NewStreamReader`?

**Comment by wonga00** [comment]
also shouldn't we update the tests?

**Comment by wonga00** [comment]
aside from extra test code, r+

**Pull request closed without merging**
